"""Phase 3 — persistence and audit log.

A SQLite journal (stdlib ``sqlite3``, no ORM, so the file stays inspectable)
of every proposal (with its option legs), reasoning stage, policy decision,
approval, order, fill, and account snapshot, so each action AEGIS takes is
auditable and replayable after the fact. WAL journaling lets a dashboard
read while the loop writes. The schema lives in versioned SQL files under
``migrations/``, applied by ``open_store`` and tracked in ``schema_version``;
failures are wrapped in ``StoreError`` with context, like ``DataError`` in
the data layer.

Since Phase 6 an order can be tied to the decision that authorised it:
``claim_order`` writes such an order (the last check of the controls and
the daily trade cap, and the first record, in one transaction) and
``apply_broker_update`` moves it on as the broker reports, recording fills
by the broker's cumulative figures.

Since Phase 5 it also holds the operator's ``controls`` — the kill switch
and the daily-loss halt — so that both survive a restart. ``get_controls``
reads them and fails closed; ``set_kill_switch`` / ``set_halt_until`` write
them, each with its audit event in the same transaction.
"""

from aegis.store.db import connect, migrate, open_store, schema_version
from aegis.store.errors import ClaimRefused, StoreError
from aegis.store.models import (
    OPEN_ORDER_STATUSES,
    TERMINAL_ORDER_STATUSES,
    Approval,
    ApprovalResponse,
    Broker,
    Controls,
    DecisionPurpose,
    Event,
    EventLevel,
    Fill,
    Instrument,
    Order,
    OrderSide,
    OrderStatus,
    OrderType,
    PnlSnapshot,
    PolicyDecision,
    PositionIntent,
    PositionSnapshot,
    Proposal,
    ProposalLeg,
    ProposalTrace,
    Reasoning,
    ReasoningStage,
    StoreStatus,
    TimeInForce,
    TokenUsage,
    Verdict,
    new_id,
)
from aegis.store.repo import (
    add_reasoning,
    apply_broker_update,
    claim_order,
    count_orders_submitted_between,
    get_controls,
    get_cycle_reasoning,
    get_cycle_token_usage,
    get_daily_pnl,
    get_decision,
    get_decision_approval,
    get_execution_orders,
    get_latest_undecided_proposal,
    get_latest_verdict,
    get_live_approvals,
    get_open_orders,
    get_order,
    get_order_by_broker_id,
    get_proposal,
    get_proposal_legs,
    get_proposal_order,
    get_proposal_trace,
    get_proposals_since,
    get_recent_events,
    get_recent_proposals,
    get_token_usage,
    get_token_usage_by_model,
    get_verdicts_since,
    insert_proposal,
    link_reasoning_to_proposal,
    log_event,
    record_approval,
    record_decision,
    record_fill,
    set_halt_until,
    set_kill_switch,
    snapshot_pnl,
    snapshot_positions,
    upsert_order,
)

__all__ = [
    "OPEN_ORDER_STATUSES",
    "TERMINAL_ORDER_STATUSES",
    "Approval",
    "ApprovalResponse",
    "Broker",
    "ClaimRefused",
    "Controls",
    "DecisionPurpose",
    "Event",
    "EventLevel",
    "Fill",
    "Instrument",
    "Order",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "PnlSnapshot",
    "PolicyDecision",
    "PositionIntent",
    "PositionSnapshot",
    "Proposal",
    "ProposalLeg",
    "ProposalTrace",
    "Reasoning",
    "ReasoningStage",
    "StoreError",
    "StoreStatus",
    "TimeInForce",
    "TokenUsage",
    "Verdict",
    "add_reasoning",
    "apply_broker_update",
    "claim_order",
    "connect",
    "count_orders_submitted_between",
    "get_controls",
    "get_cycle_reasoning",
    "get_cycle_token_usage",
    "get_daily_pnl",
    "get_decision",
    "get_decision_approval",
    "get_execution_orders",
    "get_latest_undecided_proposal",
    "get_latest_verdict",
    "get_live_approvals",
    "get_open_orders",
    "get_order",
    "get_order_by_broker_id",
    "get_proposal",
    "get_proposal_legs",
    "get_proposal_order",
    "get_proposal_trace",
    "get_proposals_since",
    "get_recent_events",
    "get_recent_proposals",
    "get_token_usage",
    "get_token_usage_by_model",
    "get_verdicts_since",
    "insert_proposal",
    "link_reasoning_to_proposal",
    "log_event",
    "migrate",
    "new_id",
    "open_store",
    "record_approval",
    "record_decision",
    "record_fill",
    "schema_version",
    "set_halt_until",
    "set_kill_switch",
    "snapshot_pnl",
    "snapshot_positions",
    "upsert_order",
]
